/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __LINK_LIST_DEMO_SKEL_H__
#define __LINK_LIST_DEMO_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct link_list_demo {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;

#ifdef __cplusplus
	static inline struct link_list_demo *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct link_list_demo *open_and_load();
	static inline int load(struct link_list_demo *skel);
	static inline int attach(struct link_list_demo *skel);
	static inline void detach(struct link_list_demo *skel);
	static inline void destroy(struct link_list_demo *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
link_list_demo__destroy(struct link_list_demo *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
link_list_demo__create_skeleton(struct link_list_demo *obj);

static inline struct link_list_demo *
link_list_demo__open_opts(const struct bpf_object_open_opts *opts)
{
	struct link_list_demo *obj;
	int err;

	obj = (struct link_list_demo *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = link_list_demo__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	link_list_demo__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct link_list_demo *
link_list_demo__open(void)
{
	return link_list_demo__open_opts(NULL);
}

static inline int
link_list_demo__load(struct link_list_demo *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct link_list_demo *
link_list_demo__open_and_load(void)
{
	struct link_list_demo *obj;
	int err;

	obj = link_list_demo__open();
	if (!obj)
		return NULL;
	err = link_list_demo__load(obj);
	if (err) {
		link_list_demo__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
link_list_demo__attach(struct link_list_demo *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
link_list_demo__detach(struct link_list_demo *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *link_list_demo__elf_bytes(size_t *sz);

static inline int
link_list_demo__create_skeleton(struct link_list_demo *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "link_list_demo";
	s->obj = &obj->obj;

	s->data = (void *)link_list_demo__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *link_list_demo__elf_bytes(size_t *sz)
{
	*sz = 488;
	return (const void *)"\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xa8\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x05\0\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x15\0\0\0\x04\0\xf1\xff\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2e\x74\x65\x78\x74\0\x2e\x6c\x6c\x76\x6d\x5f\
\x61\x64\x64\x72\x73\x69\x67\0\x6c\x69\x6e\x6b\x5f\x6c\x69\x73\x74\x5f\x64\x65\
\x6d\x6f\x2e\x63\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x26\0\0\0\x03\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x70\0\0\0\0\0\0\0\x36\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x07\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\
\x70\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x2e\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\
\x30\0\0\0\0\0\0\0\x01\0\0\0\x02\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";
}

#ifdef __cplusplus
struct link_list_demo *link_list_demo::open(const struct bpf_object_open_opts *opts) { return link_list_demo__open_opts(opts); }
struct link_list_demo *link_list_demo::open_and_load() { return link_list_demo__open_and_load(); }
int link_list_demo::load(struct link_list_demo *skel) { return link_list_demo__load(skel); }
int link_list_demo::attach(struct link_list_demo *skel) { return link_list_demo__attach(skel); }
void link_list_demo::detach(struct link_list_demo *skel) { link_list_demo__detach(skel); }
void link_list_demo::destroy(struct link_list_demo *skel) { link_list_demo__destroy(skel); }
const void *link_list_demo::elf_bytes(size_t *sz) { return link_list_demo__elf_bytes(sz); }
#endif /* __cplusplus */


#endif /* __LINK_LIST_DEMO_SKEL_H__ */
